import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';

import '@/style/main.min.css';

const montserrat = Montserrat({
  weight: ['200', '300', '400', '500'],
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode; }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
